### ISSUE TITLE
Invalid link created by discord notification

### ISSUE THREAD

**Issue by kingolifan** [AliMickey/starlink-firmware-track#2]
![image](https://user-images.githubusercontent.com/20733307/152849163-32272adc-6acd-4610-aaf9-a4552e211f3c.png)

Clicking on "Link" leads to this:
![image](https://user-images.githubusercontent.com/20733307/152849140-be4dfd0d-be57-4ba9-843f-c26400378e53.png)

Opening this leads to an error. If I understand this correctly, the link should be `https://starlink.app.mickit.net/firmware/dishy` in this case.

Not really sure how to fix this, which is why I opened an issue instead of a PR. But I guess the issue originates here: https://github.com/AliMickey/starlink-firmware-track/blob/0533e799dc863c6e3071e5036f1a25d47f7dd4c9/starlink/firmware.py#L99

**Comment by AliMickey** [comment]
Yep, thanks for that. Im currently actually reworking the website. Will be releasing the fix for this and the PR as well. Thank you!
