### ISSUE TITLE
Validating input on "add" form

### ISSUE THREAD

**Issue by NelsonMinar** [AliMickey/starlink-firmware-track#5]
I think if we add a little protection to the add form now it will save some moderation work in the future. Some rules to check the input to the add form

1. Verify the added firmware version isn't already in the database, to prevent a likely mistake. Simplest is just to reject any duplicates. But it might make sense to update the discussion URL if it wasn't set before. Should not reset the date. 
2. Verify the submitted URL has a hostname of reddit.com, to make spamming the site much less appealing.

(we could also verify the format of the Dishy firmware strings, but I think that may create problems. The format has already changed once.)

**Comment by AliMickey** [comment]
Sounds good. Will implement soon.

**Comment by AliMickey** [comment]
Implemented input validation as well as rate limiting. 

Please check for any bugs.

Thanks

**Comment by NelsonMinar** [comment]
Nice job! Tested it and it all looks OK to me.
